### PR TITLE
Fix error in synchronisation logic

### LINKED ISSUE #22: Problem with syncing record changes in v0.10.0
After updating to v0.10.0 Padlock Cloud synchronization works only when new records are created.
Deleting and updating records (adding/removing/updating fields) actions are not synchronized.
This problem is manifesting both ways on following setup:
Chrome app on PC (Win8.1, Chrome 45.0.2454.101) with iPhone app (iOS 9.0.2).

### PR DESCRIPTION
**Pull request by MaKleSoft**
Fixes #22

### CODE REVIEW

**Comment by MaKleSoft** [comment]
@inikolic This should fix #22 . Would you be so nice and verify this?

**Comment by inikolic** [comment]
how to check? update app, or I could run fixed version online?
I've tried with current installed apps, but bug is still occurring.

**Comment by MaKleSoft** [comment]
@inikolic Oh, sorry, I was just assuming you had a development version running locally. Never mind... I've tested it locally and it seems to solve the problem.

**Comment by inikolic** [comment]
@MaKleSoft Np, I've been in IT development for 20 years but got overburned and 18 mths ago changed career. So now I'm just a simple user (with some insight into the process).   ;-)

**Pull request merged**
